import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  deterrents: [{type: 'autogenerated', dirName: 'deterrents'}],
  services: [{type: 'autogenerated', dirName: 'services'}],
};

export default sidebars;
