import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  deterrents: [{type: 'autogenerated', dirName: 'deterrents'}],
  systems: [{type: 'autogenerated', dirName: 'systems'}],
};

export default sidebars;
