import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mitigations: [{type: 'autogenerated', dirName: 'mitigations'}],
  systems: [{type: 'autogenerated', dirName: 'systems'}],
};

export default sidebars;
